[package]

name = "rustychip"
version = "0.0.1"
authors = ["Joey Pereira <joey@pereira.io>"]

[[bin]]

name = "rustychip"
path = "rustychip/main.rs"

[dependencies]
getopts = "0.2"
sdl2 = "0.31.0"
time = "0.1.33"