[package]

name = "rustyemulator"
version = "0.0.1"
authors = ["Joey Pereira <joey@pereira.io>"]
edition = "2018"

[[bin]]

name = "rustyemulator"
path = "src/main.rs"

[dependencies]
getopts = "0.2"
sdl2 = "0.34"
time = "0.2"
